apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
  labels:
    app: notification-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
        - name: notification-svc
          image: aparnasukesh/notification-svc:latest
          ports:
            - containerPort: 5051
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    app: notification-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5051
      targetPort: 5051
  selector:
    app: notification-svc
