# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: notification-svc
#   labels:
#     app: notification-svc
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: notification-svc
#   template:
#     metadata:
#       labels:
#         app: notification-svc
#     spec:
#       containers:
#         - name: notification-svc
#           image: aparnasukesh/notification-svc:latest
#           ports:
#             - containerPort: 5051
#           resources:
#             requests:
#               memory: "128Mi"
#               cpu: "250m"
#             limits:
#               memory: "256Mi"
#               cpu: "500m"
#           env:
#             - name: RABBITMQ_URL
#               value: "amqp://user:password@rabbitmq:5672/"  # RabbitMQ connection string
#             - name: MONGO_URI
#               value: "mongodb://root:rootpassword@mongodb:27017/notification-db"  # MongoDB URI

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: notification-svc
#   labels:
#     app: notification-svc
# spec:
#   type: LoadBalancer  # Change to ClusterIP or NodePort for local development
#   ports:
#     - port: 5051
#       targetPort: 5051
#   selector:
#     app: notification-svc


apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
  labels:
    app: notification-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
        - name: notification-svc
          image: aparnasukesh/notification-svc:latest
          ports:
            - containerPort: 5051
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGOHOST
              value: "mongodb"  # The name of the MongoDB service
            - name: MONGODBNAME
              value: "notification-db"  # MongoDB database name
            - name: MONGOUSER
              value: "root"  # MongoDB root username
            - name: MONGOPASSWORD
              value: "rootpassword"  # MongoDB root password
            - name: MONGOPORT
              value: "27017"  # MongoDB port
            - name: GRPCPORT
              value: "5051"  # gRPC server port
            - name: EMAIL
              value: "brocampaparnasukesh@gmail.com"
            - name: PASSWORD
              value: "efdr kflf xnns fbkb"  # Ensure the password is correct for your email setup

---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    app: notification-svc
spec:
  type: LoadBalancer
  ports:
    - port: 5051
      targetPort: 5051
  selector:
    app: notification-svc
